login:
  handler: 'src/handlers/auth/login.handler'
  events:
    - http:
        method: post
        path: 'v1/auth/login'
        cors: true

signup:
  handler: 'src/handlers/auth/signup.handler'
  events:
    - http:
        method: post
        path: 'v1/auth/signup'
        cors: true        

userAuthHandler:
  handler: src/authorizers/user.auth.handler        